# Generated by Django 3.2.8 on 2021-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_Title',
            field=models.CharField(default='playlist', max_length=100),
            preserve_default=False,
        ),
    ]
